#!/bin/bash

# Script to help migrate ProjectChimera to iOS
echo "ProjectChimera iOS Migration Helper"
echo "=================================="
echo ""
echo "To run this app on iOS, you need to:"
echo ""
echo "1. Open Xcode"
echo "2. Create a new iOS App project:"
echo "   - File → New → Project"
echo "   - Choose 'iOS' → 'App'"
echo "   - Name: ProjectChimera"
echo "   - iOS Deployment Target: 17.0 (IMPORTANT!)"
echo "   - Choose your team and bundle identifier"
echo ""
echo "3. Copy these files to your new iOS project:"
echo "   - All .swift files in the current directory"
echo "   - Assets.xcassets folder"
echo ""
echo "4. In the iOS project settings:"
echo "   - Set iOS Deployment Target to 17.0"
echo "   - Add all Swift files to the target"
echo ""
echo "5. The app should then build and run on iOS!"
echo ""
echo "Note: Make sure your iPhone 16 Pro is running iOS 17.0 or later."
